[package]
name = "z39-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mptc = { path = "../mptc" }
evergreen = { path = "../evergreen" }
log = "0.4"
der-parser = "9.0.0"
