[workspace]
resolver = "2"
members = [
  "mptc",
  "marctk",
  "evergreen",
  "sip2",
  "sip2-mediator",
  "kcls",
  "evergreen-serde",
]
default-members = [
  "mptc",
  "marctk",
  "sip2",
  "evergreen",
]
