[workspace]
resolver = "2"
members = [
  "mptc",
  "marc",
  "evergreen",
  "sip2",
  "sip2-mediator",
  "kcls",
]
exclude = [
  # Keeping for reference
  "sip2-server",
]
default-members = [
  "mptc",
  "marc",
  "sip2",
  "evergreen",
]
