[workspace]
resolver = "2"
members = [
  "mptc",
  "marctk",
  "evergreen",
  "sip2",
  "sip2-mediator",
  "z39-types",
  "z39-server",
  "kcls",
]
default-members = [
  "mptc",
  "marctk",
  "sip2",
  "evergreen",
]
