[package]
name = "sip2"
version = "0.3.3"
authors = ["Bill Erickson <berickxx@gmail.com>"]
edition = "2021"
license-file = "../LICENSE"
description = "SIP2 Library"
readme = "README.md"
keywords = ["sip", "sip2", "library"]
categories = ["development-tools", "network-programming", "parser-implementations", "value-formatting"]
repository = "https://github.com/kcls/evergreen-universe-rs"

[dependencies]
chrono = "0.4.39"
deunicode = "1.6.0"
getopts = "0.2.21"
json = { version = "0.12.4", optional = true }
log = "0.4.22"

[[bin]]
name = "sip2-client-cli"

[features]
json = ["dep:json"]
