[package]
name = "opensrf"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.5"
log = "0.4.17"
syslog = "6.0.1"
serde_json = "1.0.96"                                                          
roxmltree = "0.18"
redis = "0.22.1"
gethostname = "0.4"
tungstenite = "0.19.0"
signal-hook = "0.3"

[[bin]]
name = "opensrf-router"
path = "src/bin/router.rs"

[[bin]]
name = "opensrf-websockets"
path = "src/bin/websockets.rs"

[[bin]]
name = "opensrf-buswatch"
path = "src/bin/buswatch.rs"

