[package]
name = "sip2mediator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evergreen = { path = "../evergreen" }
sip2 = { path = "../sip2", features = ["json"] }
json = "0.12.4"
log = "0.4"
uuid = { version = "1.1", features = ["v4"] }
getopts = "0.2"
syslog = "6.1"
threadpool = "1.8"
yaml-rust = "0.4"
signal-hook = "0.3"

[[bin]]
name = "eg-sip2-mediator"
path = "src/main.rs"
