[package]
name = "marc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.4"
getopts = "~0.2"

[[bin]]
name = "marc-converter"
path = "src/bin/marc-converter.rs"

